name: Ensure 15 Shop Items

on:
  schedule:
    - cron: '*/15 * * * *' # Toutes les 15 minutes
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  ensure-shop-items:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install firebase ts-node typescript
        
      - name: Install dependencies from lockfile
        run: npm ci

      - name: Run ensureShopItems script
        run: npx ts-node-esm --loader ts-node/esm scripts/ensureShopItem/index.ts
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}